### PR TITLE
Fix #564: Improve error checking logic

### LINKED ISSUE #564: Cannot request projects v2, missing scope 'read:project'
## Issue Description

*bug report*

### Describe what happened (or what feature you want)

Every time I open nvim I see the message:

```
Cannot request projects v2, missing scope 'read:project'
```

This is even after following the instructions in the README to run:

```
gh auth refresh -s read:project
```

### Describe what you expected to happen

No message to appear.

### How to reproduce it (as minimally and precisely as possible)

1. Open nvim

### Tell us your environment

MacOS 14.4.1
NVIM v0.10.0

### PR DESCRIPTION
**Pull request by relausen**
### Describe what this PR does / why we need it

Improves the error handling and user notifications when the user does not want to use Projects v2 by default, i.e., when not setting the `default_to_projects_v2` config option or setting it to `false`.

In the current code users see an unexpected error message about missing `gh` token scopes in two different scenarios:

1. They did not enable `default_to_projects_v2` and they do not have the `read:project` or the `project` scopes in their `gh` token
2.  They do have either the `read:project` or the `project` scope in their `gh` token but have not set the `default_to_projects_v2` or have set it to `false`.

In other words: They will always receive an error message if `default_to_projects_v2` is disabled.

They should only recive an error message if they enable `default_to_projects_v2` and do not have one of the necessary scopes in their token.

The PR changes the logic in the check such that it only checks for token scopes if the user actually enables `default_to_projects_v2`.

I believe this change makes the "how to suppress the error" part in the corresponding section in the FAQ unnecessary, but I'm not sure. Please let me know if this assumption is correct, and I will update the README as part of this PR.

### Does this pull request fix one issue?

Fixes #564

### Describe how you did it

Changed a conditional checking both `default_to_projects_v2` and token set conditions (using `and`) to instead check for `default_to_projects_v2` first. If that is not set to `true` then we don't need to check for scopes.

### Describe how to verify it

1. Do not set `default_to_projects_v2` or set it to `false` in the Octo config. Ensure that the `project` and `read:project` scopes are _not_ set. Load the plugin and confirm that no error message is shown.
4. Like 1, but set one of the scopes.
5. Set `default_to_projects_v2` to `true`. Ensure that the `project` and `read:project` scopes are _not_ set. Load the plugin and confirm that an error message is shown.
6. Set `default_to_projects_v2` to `true`. Ensure that the `project` and `read:project` scopes are set. Load the plugin and confirm that an error message is _not_ shown.

### Checklist

- [x] Passing tests and linting standards
- [ ] Documentation updates in README.md and doc/octo.txt

### CODE REVIEW

**Comment by wd60622** [comment]
Hi @relausen 
Thanks for making a PR! I will take a look when I can

**Comment by pwntester** [comment]
Thanks for the PR, LGTM 👍🏼

**Comment by TheLeoP** [comment]
Could an option to silence the `Using Projects V2` message be added? It's noisy to always show it on startup

**Comment by relausen** [comment]
> Could an option to silence the `Using Projects V2` message be added? It's noisy to always show it on startup

It was an honest oversight from my side that it wasn't removed before I submitted the PR. I added it for testing, and forgot to delete it. It is perfectly fine with me to have it removed completely :-)

**Pull request merged**
