### PR TITLE
fix: remove escape_char since we are now using """ quoted strings

### LINKED ISSUE #613: Quotes are being escaped
After saving an issue, the \" character is being escaped

Testing with '

Seems to only be happening with the \" character

Using `gh` version 2.57.0

### PR DESCRIPTION
**Pull request by pwntester**
### Does this pull request fix one issue?

Closes #613

### Special notes for reviews

### CODE REVIEW

**Comment by wd60622** [comment]
I am having that this works for two double quotes but I am getting an error from `gh` CLI when doing a single double quote.

**Comment by pwntester** [comment]
You are right, I think the problem is to have a double quote at the end of the comment body since it gets followed by the closing `"""` double quotes and it will unbalance the quotes. However, that does not happen when you add a leading `"` and no trailing one 🤔

**Review by wd60622 — APPROVED** [review]
Working for me. Just has the issue when one `\"` is at the end of the comment block. But that shouldn't be a blocker

**Comment by wd60622** [comment]
This one good to merge?

**Pull request merged**
