### PR TITLE
feat: develop issue in remote repo

### LINKED ISSUE #695: Develop issue in separate repository
## Issue Description

Currently, the `issue develop` command assumes that the issue you want to develop is owned by the same repository that you want to host the development branch. However, it's not uncommon to have one set of GitHub repos that host issues, and another set of GitHub repos that host code.

It would be nice if the `issue develop` command were able to support this.

### Describe what happened (or what feature you want)

Let's say I am working in my local clone of a `mycode` repo  (which doesn't contain any issues), with the `main` branch checked out. 

Separately, I have a `myissues` repo which contains 1 issue. I go to my local `mycode` clone, edit issue #1 in the `myissues` repo, and try to start development.

 1. `Octo issue myorg/myissues edit 1`
 2. `Octo issue develop`

What happens is that Octo runs `gh issue develop 1 --checkout` in the context of the `mycode` repo. But `mycode` doesn't contain issue #1. The command says that it checks out the `main` branch. In fact the command has failed, but it's not obvious why.

### Describe what you expected to happen

The command should either report why it has failed, or even nicer, supply the `--repo` and `--branch-repo` arguments to the `gh issue develop` command.

### How to reproduce it (as minimally and precisely as possible)

1. Create an issue in one repository. Let's say it lives at `myorg/myissues/issue/1`.
4. Clone another repository, let's call it `myorg/mycode`, which doesn't have any issues, and checkout the `main` branch.
5. Open neovim in the local clone.
6. Run `Octo issue edit myorg/myissues 1`.
7. Run `Octo issue develop`.

### Tell us your environment

**Mac**
image

**nvim**
```sh
❯ nvim --version
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info
```

**LazyVim**

```sh
~/.c/nvim main
❯ git show HEAD~2 --pretty=format:"%h" --no-patch

79b3f27
```

### PR DESCRIPTION
**Pull request by maxenglander**
### Describe what this PR does / why we need it

This PR makes it possible to use `Octo issue develop` when the issue in question is not owned by the repo where the development is happening.

### Does this pull request fix one issue?

Fixes #695.

### Describe how you did it

Supply `--repo` and `--branch-repo` args to `gh issue develop`.

### Describe how to verify it

 1. Create a first issue 1 in `myorg/myissues`.
 2. Locally, checkout `main` branch of `myorg/mycode`.
 3. Open neovim.
 4. Run `Octo issue edit myorg/myissues 1`.
 5. Run `Octo issue develop`.

Octo should report that it has created a branch `1-<issue-name>`. Running `git status` locally should show that checked out branch is named `1-<issue-name>`.

You can also just do:

 4. Run `October issue develop myorg/myissues`.
 5. Select issue 1.

And the result should be the same.

### Checklist

- [x] Passing tests and linting standards
- [ ] Documentation updates in README.md and doc/octo.txt

### CODE REVIEW

**Comment by wd60622** [comment]
Thanks for PR! Will take a look when I can

**Comment by wd60622** [comment]
This works fine for me with the previous cases. I don't have a remote repo to test this on, however.

Maybe @GuillaumeLagrange does?

**Review by wd60622 — APPROVED** [review]
Looks good to me!

**Comment by maxenglander** [comment]
@wd60622 just invited you to be a collaborator on https://github.com/maxenglander/octo.nvim in case you wanna use that as the remote repo.

**Pull request merged**
