### PR TITLE
Add template support

### LINKED ISSUE #304: Feature - Respect PR template when creating a new PR.
## Issue Description

Type: *feature request*

### Describe 
When creating a new PR  using octo, repect the Pull request template stored in `.github/PULL_REQUEST_TEMPLATE.md` of the REPO . Currently Octo creates a PR with empty descritption. 
### References
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

### PR DESCRIPTION
**Pull request by pwntester**
### Describe what this PR does / why we need it
This PR adds support for using templates to create both issues and PRs

### Does this pull request fix one issue?
Fixes #304

### Describe how you did it
When creating a new issue or PR, Octo will check if the repo has template defined for them and if so will offer to use them using a telescope menu
So far, it will create the issue/PR with the basic template, and users need to edit the template __after__ the issue/PR is created which is not ideal.

### CODE REVIEW

**Comment by shivanth** [comment]
I successfully created a pr using a template using this branch. :+1

**Comment by blakedietz** [comment]
> I successfully created a pr using a template using this branch. :+1

Any tips on how I could use packer to switch to this branch temporarily to help with testing?

**Comment by shivanth** [comment]
Use `branch` key in packerc onfiguration.
Example copied from packer readme: 

```
  use {
    'glepnir/galaxyline.nvim', branch = 'main', config = function() require'statusline' end,
    requires = {'kyazdani42/nvim-web-devicons'}
  }
```

**Comment by sozoalvin** [comment]
Will this PR be merged soon? Is there anything I can do to help?

**Comment by pwntester** [comment]
I think its fine to get this merged. Let me know if you find any problems

**Comment by sozoalvin** [comment]
@pwntester will update octo and try it out - will provide feedback if any! thanks for all that you do

**Comment by sozoalvin** [comment]
sorry ; how do you create a PR using templates? (i realised you talked about a telescope window opening) do you just run `:Octo pr create` ? if yes, mine has a little window that slides up and after putting in title , base branch values , comes up with an error:

Screenshot 2022-09-14 at 10 51 39 AM

**Comment by pwntester** [comment]
Seems like you got `nil` instead of the template body so for some reason it failed to grab the template for your PRs. Can you share the repo you are using if public or let me know whats the PR template and where its located?

**Comment by sozoalvin** [comment]
ah; its not a public repo - but i can try to create a public repo with the sample template to see if i can get the same error

just checking, is there should the file sit and be named in such a folder/ directory? 

`github/PULL_REQUEST_TEMPALTE.MD`

**Comment by pwntester** [comment]
The path looks correct except its missing a leading dot `.github`

**Comment by sozoalvin** [comment]
yep it to be exact, the path is indeed as you mentioned. i forgot to type the `.` 

one more thing; i installed octo using vimplug instead of packer; would this have caused isuses?

**Comment by pwntester** [comment]
No, that shouldnt be a problem. I use a different one and all of them should be doing the same

**Comment by sozoalvin** [comment]
Dear @pwntester  thank you. I think there was something wrong with my installation - having said that I think something is off and there is no longer an error. 

But can i just confirm that when you try to create a PR using octo, the inputs for PR title will be via the little box that slides open on the bottom left of nvim ? 

(is there an ongoing feature that allows editing via a nvim editor instead?) 

P.S. thank you so much for your help

**Comment by pwntester** [comment]
We use `vim.fn.input()` which can be "hijacked" by plugins to present the input form in different ways. Without any plugins, you should get the input prompt in the command line. It seems you may be using something like https://github.com/stevearc/dressing.nvim

**Pull request merged**
