### PR TITLE
feat: provide entry filename for better integration with nvim

### PR DESCRIPTION
**Pull request by muniter**
### Describe what this PR does / why we need it

By providing the filename as part of the entry, now a user can load multiple
entries from Telescope to the quickfix/loclist and actually move through them
and making Octo fill the buffers by triggering the BufReadCmd.

### Does this pull request fix one issue?

I don't see one, but I think this is an actual bug. Before this code if you tried filling the quickfix list you wouldn't get anything useful.

### Describe how you did it

Break up editing function into uri generation and editing the uri.

### Describe how to verify it

1. `Octo issue list`
2. Select multiple with telescope
3. Use send to quickfix/loclist action.
4. Now navigation of the quickfix list has the buffer names, and Octo fills them.

### Special notes for reviews

I tested pull requests and issues, but not the repo one. Can't seem to make octo show me the repositores I own. Or perhaps I made a mistake?

### CODE REVIEW

**Review by pwntester — APPROVED** [review]

**Comment by pwntester** [comment]
Thanks! Havent used the Telescope to QF action yet, but this sounds pretty cool. Can you please take a look to the stylua check?

**Comment by jlopezgr** [comment]
The linter was complaining about files I didn't touch, but I wen ahead and added those changes to the commit. Is that ok?

**Comment by muniter** [comment]
The linter was complaining about files I didn't touch, but I wen ahead and added those changes to the commit. Is that ok?

**Review by pwntester — APPROVED** [review]

**Comment by pwntester** [comment]
> The linter was complaining about files I didn't touch, but I wen ahead and added those changes to the commit. Is that ok?

Yep, those are checks that keep failing, need to take a look and fix them

Thanks again for the contribution, keep them comming!

**Pull request merged**
