### PR TITLE
Fix #221

### LINKED ISSUE #221: Error trying to assign a user to an issue
## Issue Description

*bug report*

### Describe what happened (or what feature you want)
Three problems:
1. When I hit space-aa the telescope window appears with the corners not showing (font: Meslo LGS NF)
2. When I start typing I get an indicator `1/1` but no option to select
3. If I hit enter an exception is raised on the close method call of the picker
```
E5108: Error executing lua ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:251: Vim(lua):E5108: Error executing lua ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1300: attempt to index field 'finder' (a function
value)
stack traceback:
        ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1300: in function 'on_close_prompt'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_win_close'
        ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:251: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function '_close'
        .../start/octo.nvim/lua/octo/pickers/telescope/provider.lua:859: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:235: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'nvim_win_close'
        ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:251: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function '_close'
        .../start/octo.nvim/lua/octo/pickers/telescope/provider.lua:859: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:235: in function 'execute_keymap'
```

### Describe what you expected to happen
I should be able to self-assign an issue, or assign other people

### How to reproduce it (as minimally and precisely as possible)

1. :Octo issue list
2. Select an issue
3. space-aa
4. Type in a name and hit enter

### Tell us your environment
- MacOS BigSur 11.3.1
- NVIM v0.6.0-dev+650-g04c7b5503
- Octo at commit 44df9c0486ec875a0e104d5fe70a31d1a33bf4f7
- Telescope at commit [telescope.nvim#ef245548a858690fa8f2db1f1a0eaf41b93a6ef6](https://github.com/nvim-telescope/telescope.nvim/commit/ef245548a858690fa8f2db1f1a0eaf41b93a6ef6)
- gh installed with brew

### Anything else we need to know?
No.

### PR DESCRIPTION
**Pull request by pwntester**

### CODE REVIEW

**Comment by waltermaldonado** [comment]
It is working now, only exception to the corners of the dialog:

image

Wondering if we could remove the hardcoded borders here and let Telescope handle them?
https://github.com/pwntester/octo.nvim/blob/c030f5b5fc93e66a6765d9ba7e0ca5764ee72238/lua/octo/pickers/telescope/provider.lua#L26

image

**Comment by waltermaldonado** [comment]
Oh, there is something here. As you can see, the indicator show `27/27`, but we have 11 names being showed:
image

**Comment by pwntester** [comment]
I removed the hardcoded borders, and changed the other dynamic searches. As for the x/y numbers. I think those indicate the number of results, not the one shown in the results window. You ahould be able to scroll down or move the selected row to see the others, but thats a Telescope thing. I can also remove the hardcoded window dimension to accomodate more results. Let me know if it works for you.

**Comment by waltermaldonado** [comment]
I think this is very good, thanks for addressing this so quickly and accepting the suggestions. I am experiencing a strange highlight effect as long as I scroll down, but is can be something related to other configs of mine.

Thank you very much.

**Comment by pwntester** [comment]
Cool, thank you for the heads up!

**Pull request merged**
