### PR TITLE
Synched review comments

### PR DESCRIPTION
**Pull request by pwntester**
Addresses #118 

- [x] save comments to GH
- [x] implement `Octo review  resume`
- [x] implement `Octo review discard`
- [x] on resume: fetch review comments and populate review_comments table
- [x] jump to comment in `Octo review comments`
- [x] fix comment signs

### CODE REVIEW

**Comment by weilbith** [comment]
How can I resume a comment in a line I have already added one? I just tried it with `<space>ca` on the exact same line, but this always gives me an empty comment window.

**Comment by pwntester** [comment]
try using `Octo review comments` and then `<c-e>`, or `Octo comment edit` on the line of the comment you want to edit.

Yep, this needs better documentation

**Comment by weilbith** [comment]
Okay so is it a use-case to have multiple comments to the same line of code? Or could we just edit an existing comment if it does exist already? :thinking: 
But I guess it is worth to keep this as a feature. Is there already a mapping for `Octo comment edit`? Like `<space>ce`?

**Comment by pwntester** [comment]
> Okay so is it a use-case to have multiple comments to the same line of code? Or could we just edit an existing comment if it does exist already? 🤔

Not sure. I don't see a reason to add several comments in the same line, but I guess some people will find valid uses cases. This may not be supported currently as the key for `reviews._review_comments` is based on the comment's side, path and lines. So two comments on the same side/path/lines will override the previous one 🤔 

> But I guess it is worth to keep this as a feature. Is there already a mapping for Octo comment edit? Like <space>ce?

No, but it should be. I will add it

**Comment by weilbith** [comment]
> So two comments on the same side/path/lines will override the previous one thinking

You lost me. Why?

>    But I guess it is worth to keep this as a feature. Is there already a mapping for Octo comment edit? Like ce?
 No, but it should be. I will add it
 
 Which reminds me that it is quite hard to add custom mappings. For the issue/PR buffer there is a special filetype and the user can define an `after/ftplugin/...` for it. Wait a sec. This reminds me that the filetype is `octo_issue`. The `ftplugin` syntax for Vim works like that it searches for `ftplugin/{filetype}_*.vim` (and in the `after/ftplugin/{filetype}_*.vim`). So you can have multiple files for the same filetype and postfix them with like `java_mappings.vim` and `java_options.vim`. Or you can define a directory like `ftplugin/{filetype}/*.vim`. But with `octo_issue` this does not work. I had this issue already once back then with another plugin. We want to fix that I think.

**Comment by pwntester** [comment]
> You lost me. Why?

Comments are currently stored in a table using the comment bufname as the key (eg: `octo://pwntester/octo.nvim/pull/94/comment/RIGHT/README.md:128.128`) which means that two comments on the same side/path/startLine/line will collide and the last one will override the first one. I will fix this by using the GitHub id as the key

**Pull request merged**
