### PR TITLE
feat(picker): add config options for changing mappings

### LINKED ISSUE #447: Feature Request: add config options to change picker mappings
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

I'd like the ability to change the Telescope mappings set by this plugin. Specifically, I use `<C-b>` to scroll the preview up, and I always accidentally open issues/prs in the browser when using Octo.

### Describe what you expected to happen

The ability to change Telescope mappings, which are currently hard-coded.

### How to reproduce it (as minimally and precisely as possible)

N/A (not a bug)

### Tell us your environment

N/A (not a bug)

### Anything else we need to know?

I submitted a pull request for this issue: #448

### PR DESCRIPTION
**Pull request by benelan**
### Describe what this PR does / why we need it

Adds config options to change the telescope or fzf-lua mappings.

### Does this pull request fix one issue?

Fixes #447

### Describe how you did it

I added the the config options and used them in the telescope and fzf-lua picker code. I added a util, along with spec tests, that converts vim style mappings to fzf ones.

### Describe how to verify it

1. Change `pwntester/octo.nvim` to `benelan/octo.nvim` in your Neovim plugin config
2. Add the following to your Octo config

    ```lua
    picker_config = {
      mappings = {
        open_in_browser = { lhs = "<M-b>", desc = "open issue in browser" },
        copy_url = { lhs = "<M-y>", desc = "copy url to system clipboard" },
        checkout_pr = { lhs = "<M-o>", desc = "checkout pull request" },
        merge_pr = { lhs = "<M-r>", desc = "merge pull request" },
      },
    },
    ```
3. Open an Octo telescope or fzf-lua picker, e.g. `Octo pr list`
4. Verify that the mappings are triggered with alt instead of ctrl (which is the default)

### Special notes for reviews

The `desc` property isn't used, but I added it to match the format of the other mappings in the config. Plus, Telescope may add the ability to use the `desc` for `<C-/>` some day.

Let me know if you'd like me to change anything about the config options I added, thanks for the review!

### CODE REVIEW

**Review by pwntester — CHANGES_REQUESTED** [review]
Thanks for the PR! Can you please apply similar changes to fzf-lua picker provider?

**Comment by benelan** [comment]
Thanks for the review. I added a util to convert vim style mappings to fzf ones and the spec tests I added are passing. I also installed fzf-lua and everything is working correctly. Let me know if any other changes are required!

**Comment by pwntester** [comment]
Thanks, that looks great! Can you please fix the linter errors?

**Comment by benelan** [comment]
Woops, sorry about that. I also had to move the util for converting the mappings to the main util module because `fzf-lua` is not installed for the tests. Everything should be passing now!

**Review by pwntester — APPROVED** [review]

**Comment by pwntester** [comment]
Thanks a lot!

**Pull request merged**
