### PR TITLE
Gitlab with teal

### PR DESCRIPTION
**Pull request by l0nax**
### Does this pull request fix one issue?

* #138 (Partially)
* Ref: #282 

### Special notes for reviews

I've removed/ moved all the content from `lua/` to `src/` and _did not_ commit the new content of `lua/` otherwise it would be difficult to review what has changed (in the lua code).

If merged onto `master` the code has to be "compiled" and put into the `lua/` directory.

The code has to be "compiled" back to lua since we do not want to break the caching mechanism (slowing down the startup of Nvim):
```bash
~$ rm -rf lua/*
~$ tl build
~$ rsync -zarv --include="*/" --include="*.lua" --exclude="*" "src/" "lua/"
```

### CODE REVIEW

**Comment by pwntester** [comment]
Im sorry, but any GitLab support should be added in pure lua since Im not considering moving the project to Teal at this point

**Comment by farbodsz** [comment]
That's fair. @l0nax , do you think you'll work on a Lua-only version for this feature? If not, I'm happy to give it a go

**Comment by brendalf** [comment]
Hi folks, I'm almost there. I will open the MR this weekend.

**Comment by globin** [comment]
Any news on this?

**Pull request closed without merging**
